### ISSUE TITLE
Error trying to run:

### ISSUE THREAD

**Issue by kennysphan** [shahargl/upload-github-workflow-logs-to-elastic#3]
```
try:
    es = elasticsearch.Elasticsearch(
        [ELASTIC_HOST],
        api_key=(ELASTIC_API_KEY_ID, ELASTIC_API_KEY),
        scheme="https"
    )
```
Hi, the error i have is below but i am pretty sure the portion is causing it from above
![image](https://user-images.githubusercontent.com/77749061/179220173-2f3a9156-0310-4c65-abcd-f4bb74bd5603.png)

**Comment by sapanovych911** [comment]
hi, how I understanding issue with newest elasticsearch library - for now trying to find version for normal using this

**Comment by shahargl** [comment]
fixed
